server:
  port: 8021
spring:
  application:
    name: ms-eureka-client-north-fu
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8001/eureka
logging:
  level:
    houzm.accumulation.ms: debug